defaults:
  # - override hydra/sweeper: optuna
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s [%(levelname)s][%(module)s] %(message)s'
  # sweep:
  #   dir: ../multirun/${now:%Y-%m-%d_%H-%M-%S}
  #   subdir: ${hydra.job.num}
  # sweeper:
  #   study_name: tuning
  #   direction: minimize
  #   n_jobs: 1
  #   n_trials: 10
  #   search_space:
  #     params.seed:
  #       type: int # float
  #       low: 1
  #       high: 1000
  #       # step: 10
  #       # log: True
  #     params.n_fold:
  #       type: categorical
  #       choices: [5, 10]

wandb:
  enabled: True
  entity: imokuri
  project: ump
  dir: ${hydra:runtime.cwd}/../cache
  group: default

settings:
  print_freq: 100
  gpus: "6,7"

  dirs:
    working: ${hydra:runtime.cwd}
    input: ${hydra:runtime.cwd}/../inputs/
    feature: ${settings.dirs.input}features/
    preprocess: ${settings.dirs.input}preprocess/
    # train_image: ${settings.dirs.input}train/
    # test_image: ${settings.dirs.input}test/

  inputs:
    - train.csv
    - example_test.csv
    - example_sample_submission.csv

  debug: False
  n_debug_data: 100_000

  amp: True
  multi_gpu: True

  training_method: nn

params:
  seed: 440
  n_class: 1
  preprocess:
    - "neighbors"
  n_fold: 5
  skip_training: False
  epoch: 20
  es_patience: 0
  batch_size: 640
  gradient_acc_step: 1
  max_grad_norm: 1000
  fold: combinational_purged
  group_name: investment_id
  time_name: time_id
  label_name: target
  use_feature: True
  feature_set:
    - "f000"
    - "f100"
  dataset: ump_1
  model: ump_1dcnn
  model_input: 600
  # model_name: swin_large_patch4_window12_384_in22k
  pretrained: []
  # pretrained:
  #   - dir: ""
  #     model: ""
  #     name: ""
  # dropout: 0.0
  criterion: RMSELoss
  optimizer: Adam
  scheduler: CosineAnnealingWarmupRestarts
  lr: 1e-3
  min_lr: 1e-6
  weight_decay: 1e-5
  label_smoothing: 1e-6
  scoring: pearson
