defaults:
  # - override hydra/sweeper: optuna
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s [%(levelname)s][%(module)s] %(message)s'
  # sweep:
  #   dir: ../multirun/${now:%Y-%m-%d_%H-%M-%S}
  #   subdir: ${hydra.job.num}
  # sweeper:
  #   study_name: tuning
  #   direction: minimize
  #   n_jobs: 1
  #   n_trials: 10
  #   search_space:
  #     params.seed:
  #       type: int # float
  #       low: 1
  #       high: 1000
  #       # step: 10
  #       # log: True
  #     params.n_fold:
  #       type: categorical
  #       choices: [5, 10]

wandb:
  enabled: True
  entity: imokuri
  project: ump
  dir: ${hydra:runtime.cwd}/../cache
  group: default

settings:
  print_freq: 100
  # gpus: "6,7"
  gpus: "6"

  dirs:
    working: ${hydra:runtime.cwd}
    input: ${hydra:runtime.cwd}/../inputs/
    input_minimal: ${hydra:runtime.cwd}/../datasets/inputs/
    feature: ${settings.dirs.input}features/
    preprocess: ${settings.dirs.input}preprocess/
    # train_image: ${settings.dirs.input}train/
    # test_image: ${settings.dirs.input}test/

  inputs:
    - train.csv
    - example_test.csv
    - example_sample_submission.csv

  debug: False
  n_debug_data: 100_000

  amp: True
  multi_gpu: True

  training_method: nn

params:
  seed: 9440
  n_class: 1
  preprocess: # []
    # - "standard_scaler"
    # - "power_transformer"
    # - "pca"
    # - "ppca"
    # - "nearest_neighbors"
    - "faiss_ivfpq"
    # - "remove_china_shock"
  pca_n_components: 50
  n_fold: 5
  skip_training: False
  epoch: 5
  es_patience: 0
  batch_size: 640
  gradient_acc_step: 1
  max_grad_norm: 1000
  fold: combinational_purged
  group_name: investment_id
  time_name: time_id
  label_name: target
  use_feature: True
  feature_set:
    - "f000"  # f000_initial_features
    # - "f001"  # f001_last10_features
    # - "f100"  # f100_vs_same_time_id_average
    # - "f101"  # f101_vs_same_time_id_max
    # - "f102"  # f102_vs_same_time_id_min
    # - "f200"  # f200_lag_last_features
    # - "f201"  # f201_lag_last_3_features
    # - "f202"  # f202_lag_last_4_features
    # - "f300"  # f300_vs_nearest_neighbors_average
    - "f301"  # f301_nearest_neighbors_target (mean)
    # - "f302"  # f302_nearest_neighbors_target_min
    # - "f303"  # f303_nearest_neighbors_target_max
    - "f304"  # f304_nearest_neighbors_target_median
    # - "f400"  # f400_moving_average_short
    # - "f401"  # f401_moving_average_long
    # - "f402"  # f402_moving_average_convergence_divergence
    # - "f403"  # f403_moving_average_convergence_divergence_signal
    # - "f410"  # f410_moving_average_short_last10
    # - "f411"  # f411_moving_average_long_last10
    # - "f901"  # f901_pseudo_last_target
    # - "f902"  # f902_last10_target
  dataset: ump_1
  model: ump_1dcnn_small
  model_input: 308
  model_window: 10
  # model_name: swin_large_patch4_window12_384_in22k
  pretrained: []
  # pretrained:
  #   - dir: ""
  #     model: ""
  #     name: ""
  # dropout: 0.0
  criterion: RMSELoss
  optimizer: Adam
  scheduler: CosineAnnealingWarmupRestarts
  lr: 1e-3
  min_lr: 1e-6
  weight_decay: 1e-5
  label_smoothing: 1e-6
  scoring: pearson
